# Generated by Django 5.2 on 2025-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacksystem', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
