# Generated by Django 5.2 on 2025-05-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacksystem', '0005_feedback_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_anonymous',
        ),
    ]
